export const data = [
  {
    name: "Mecanu APP",
    skills: [
      "next",
      "react",
      "tailwind",
      "postgres",
      "html",
      "css",
      "express",
      "node",
      "javascript",
      "firebase",
    ],
    path: "/mecanu",
  },
  {
    name: "Openvino",
    skills: [
      "next",
      "react",
      "tailwind",
      "postgres",
      "html",
      "css",
      "express",
      "node",
      "javascript",
    ],
    path: "/openvino",
  },
  {
    name: "PokemonSPA",
    skills: [
      "react",
      "postgres",
      "css",
      "express",
      "node",
      "redux",
      "html",
      "node",
      "javascript",
    ],
    path: "/pokemon",
  },
  {
    name: "Netflix-clone",
    skills: [
      "react",
      "tailwind",
      "firebase",
      "firestore",
      "html",
      "javascript",
    ],
    path: "/netflix",
  },
  {
    name: "Portfolio",
    skills: ["next", "tailwind", "html", "javascript"],
    path: "/portfolio",
  },
];
